---
- name: Deploy App
  hosts: app
  become: true
  tasks:
    - name: Update repositories cache and install "git" package
#      ansible.builtin.apt:
      apt:
        name: git
        update_cache: yes
    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
#        dest: /home/appuser/reddit
        dest: /home/ubuntu/reddit
        version: monolith
      notify: reload puma
    - name: Bundle install
      bundler:
        state: present
##        chdir: /home/appuser/reddit
        chdir: /home/ubuntu/reddit
      notify: reload puma
  handlers:
    - name: reload puma
      systemd: name=puma state=restarted
